alias kctx='kubectx'
alias kstage='kubectx staging'
alias kstagef='kubectx staging-fuji'
alias kserv='kubectx services'
alias kprod='kubectx production'
alias kgn='kubectl get nodes -o wide'
alias kgp='kubectl get pods -o wide'
