alias nuphyH='kmonad ~/.config/kmonad/nuphyHard.kbd & disown'
alias nuphy='kmonad ~/.config/kmonad/nuphy.kbd & disown'
alias gmmk='kmonad ~/.config/kmonad/gmmkCompact.kbd & disown'
alias anne='kmonad ~/.config/kmonad/anneHard.kbd & disown'
alias rev='kmonad ~/.config/kmonad/reviung41.kbd & disown'
alias revh='kmonad ~/.config/kmonad/reviungH.kbd & disown'
alias revu='kmonad ~/.config/kmonad/reviungUsb.kbd & disown'
